### PR TITLE
Expected output

### PR DESCRIPTION
**Pull request by lochel**
Updated expected output for those tests that do not fail due to missing or corrupted reference files.

### CODE REVIEW

**Comment by sjoelund** [comment]
Do we really want to keep the debug dumps in the test suite?

**Comment by lochel** [comment]
I added them a while back since they got broken and no one noticed. I think we should keep them, but we could probably use smaller models for some of them (not the fullRobot one).

**Comment by sjoelund** [comment]
OK. Let's add smaller models as a pull request instead.

**Comment by sjoelund** [comment]
Are these commits ready now? Note that github does not send notifications when the pull request is updated (like for 533839e)

**Comment by lochel** [comment]
Not yet. There are some tests that dump time stamps:
  * dumpSparsePattern.mos
  * dumpSparsePatternVerbose.mos
  * symjacdumpverbose.mos

I think we should just deactivate them for now.

**Comment by sjoelund** [comment]
OMC could always check if the test suite is running and skip outputting the line or using time=0.

**Comment by lochel** [comment]
Sounds good. Then we can activate the tests again.

**Comment by sjoelund** [comment]
Fixed by 13e820f (squashed commits)

**Pull request closed without merging**
