### PR TITLE
fixed test

### PR DESCRIPTION
**Pull request by vruge**
- partial revert of PR606

### CODE REVIEW

**Comment by vruge** [comment]
@sjoelund is there a better way to revert the changes for result file?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-04-02_22-52-00](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4140/console).

**Comment by lochel** [comment]
@vruge Why should there be a discrete change of the continuous variable `y3` in the final solution?

**Comment by sjoelund** [comment]
@vruge not once the previous change was committed. We try not to commit mat-files though; only xz-compressed mat-files.

**Comment by vruge** [comment]
@sjoelund thanks, I will try to change it with xz-compressed mat-file.

**Comment by vruge** [comment]
@lochel 
Why the solution should drift away from initial guess?

**Comment by lochel** [comment]
@vruge wrote:
> Why the solution should drift away from initial guess?

Because it is not a valid solution if a continuous signal performs discrete changes without an associated event. So I still wonder why you push so hard for this kind of behaviour.

**Comment by vruge** [comment]
@lochel 
> Because it is not a valid solution if a continuous signal performs discrete changes without an associated event. 


based on your definition of discrete the model
```
model Unnamed
  Real x(start = -10);
equation 
  (1-time)*x^2 + 2*x =  1e-2*time;
end Unnamed;
```
has no  valid solution for time in [0,2]... correct?


>So I still wonder why you push so hard for this kind of behaviour.

It's really hard to make internal advertising for quality if people broken test(s) with basic functionality...

**Comment by lochel** [comment]
@vruge wrote:
> based on your definition of discrete the model
> ```
> model Unnamed
>   Real x(start = -10);
> equation 
>   (1-time)*x^2 + 2*x =  1e-2*time;
> end Unnamed;
> ```
> has no  valid solution for time in [0,2]... correct?

Well, if you pick the solution `x=0` at `time=0`, then everything is fine. But if you want to pick `x=-2` at `time=0`, then the simulation should stop at `time=1`, because of the discontinuity. So what is your point here?

Maybe you missed the email that I've send you earlier today. I propose a short web meeting to discuss your intentions and doubts regarding the latest changes.

**Comment by vruge** [comment]
@lochel 
>  So what is your point here?

I don't understand, 
- why the simulation should stop?
- why bifurcation is invalid?

Where I can find this **two** requirements  in modelica **spec**.  
This would be help me much more then a web meeting.

**Comment by vruge** [comment]
Unfortunately, no longer possible since PR1601 to use `$_old`

**Pull request closed without merging**
