### PR TITLE
Update expected output after library bump

### PR DESCRIPTION
**Pull request by lochel**
Some of the expected outputs have changed due to modelica/Modelica@943b7b9add2fdea2d2cfeacb37a0450b39617c91.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-11-24_11-41-09](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1234/).

**Comment by sjoelund** [comment]
Use the boolean FORCE_LATEST to force the latest libraries, so the tests can run against them.

**Comment by lochel** [comment]
@sjoelund Thanks!

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-25_12-31-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1247/console).

**Pull request closed without merging**
