### PR TITLE
Split synchronous features into pre and post phase

### PR DESCRIPTION
**Pull request by lochel**
see OpenModelica/OMCompiler#1391

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-25_19-34-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3789/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-26_11-23-09](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3798/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-27_09-47-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3807/).

**Comment by lochel** [comment]
@bernhard-thiele @rfranke Do you think that it is reasonable to push the changes even if some state machines (example DeadEnd and MLS33_17_3_7NA) do not work anymore with the c runtime? The examples work fine using the Cpp runtime instead. Hence, I think there is something wrong in the c runtime or in the corresponding code generation and it is not directly connected to my changes. Any comments?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-31_11-09-14](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3834/console).

**Pull request closed without merging**
