### PR TITLE
Add test for ticket 3792

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by adrpo** [comment]
Would be nice to use # before the ticket number because it will be recognized by Trac.

**Comment by lochel** [comment]
But in that case it would also be recognized as a GitHub pull request.

**Comment by sjoelund** [comment]
I sometimes write it as OM ticket #3792

**Comment by adrpo** [comment]
True, the system is a bit off :)
I'll have a look in Trac if is possible to change the # to something else.

**Comment by lochel** [comment]
That would be great and avoid a lot of wrong referenced issues on GitHub.

**Comment by sjoelund** [comment]
Can't you write ticket:3792 then?

**Pull request closed without merging**
