### PR TITLE
Test for bug #2588

### PR DESCRIPTION
**Pull request by fbergero**
This is a test for bug #2588 that should be fixed with the Pull request 303.

Extra examples could be added to see if the dumped code is valid modelica code.

### CODE REVIEW

**Comment by adrpo** [comment]
@fbergero: would be good to use # before the bug number as #2558 because then the Trac system will create links to the ticket.

**Comment by fbergero** [comment]
Sorry about that. Just fixed it.

**Comment by adrpo** [comment]
I was talking about the commit message: "Test for buf 2588".

**Comment by fbergero** [comment]
Auch didn't see the typo...should I change it?

**Comment by adrpo** [comment]
Yes, would be good to change it to: "Test for bug #2588"

**Comment by fbergero** [comment]
Just did.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-25_14-21-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1254/console).

**Pull request closed without merging**
