### PR TITLE
changed diff-tool paths with autoconf

### PR DESCRIPTION
**Pull request by MarcusWalther**
PROBLEM
Just passing the OMBUILDDIR-Variable to make does not solve the issue described in my last pull request. If somebody has checked out the OpenModelica-testsuite seperately from OMCompiler, the testsuite is not able to execute the omc-diff-executable from the right location. This is because rtest still tries to find omc-diff in the relative-path "../build". 

SOLUTION
I decided to put some autoconf-stuff in the testsuite.

Now we can run 
autoconf
./configure --with-OMBUILDDIR=<path to om-build-dir>

This will create a Makefile that includes Makefile.common, which is just the old Makefile. Besides that, it will create rtest out of rtest.in with the correct paths. If you do not specify the "--with-OMBUILDDIR" argument, the old "../build"-path is used. 

OPEN QUESTION
- The tests are not able to localize the msl, because the Perl-script executes "delete($ENV{'OPENMODELICALIBRARY'});". If I remove this line, everything is working fine. Is this line important?

REMARKS
- I also added the OpenModelica-Common-repository as submodule
- I've tested these changes on Linux and Windows
- The pull-request contains a lot of files that are part of openmodelica/cppruntime, because something went wrong with merging last time. They are not important, sorry for that.

### CODE REVIEW

**Comment by sjoelund** [comment]
Yes, deleting OMLIBRARY is important because the Windows installer sets the variable.
There is a simpler solution to finding ../build, and that is to simple not compile omc-diff into build/bin/omc-diff, keeping it in testsuite/difftool/omc-diff instead.

**Comment by MarcusWalther** [comment]
Hmm....why did you not mention this in pull request #16? I thought it is important for you, that the omc-diff executable is in the same directory as the omc executable...
Neither Windows nor Linux will find the MSL if I go to testsuite/openmodelica/cppruntime and execute "make", because the OPENMODELICALIBRARY-Variable is deleted by rtest. How should I run all tests that are inside testsuite/openmodelica/cppruntime?

**Comment by sjoelund** [comment]
Because I had to sleep on it to figure out it's not really needed in bin :)

You need to run `make omlibrary-core` to actually build MSL. Else you will use some version of MSL that does not belong with the test suite.

**Comment by MarcusWalther** [comment]
But there are still some open points:
- the omlibrary-core-target is just part of the "superproject", but I think the testsuite should be usable as "standalone version" - so we have to make the library-location configurable
- rtest is searching for the omc-executable with the command "$OPENMODELICAHOME/bin/$OMCEXE", therefore it's important to know the location of the build/bin-folder - regardless of whether omc-diff is build into the testsuite or compiler folder

In my opinion we can only handle these things with configure.

**Comment by sjoelund** [comment]
- You can go into the libraries project and select where to build the files --this could be into OMCompiler/build/lib/omlibrary or so whatever you like
- rtest does not need OPENMODELICAHOME. You can use --with-omc=/path/to/omc to use a different path.

**Comment by sjoelund** [comment]
You will need to pull, fix conflicts and rebase the branch for it to be merged (I added a hudson task to check for files that should not be committed, and also removed bad files from the repository).

**Comment by MarcusWalther** [comment]
I'm not sure how we should continue with the pull-request. I've merged my fork with the master, but I have the feeling that you don't like my changes :-). Should I just keep it in my fork and handle it on my own or should I reopen a new pull request?
I still think that the configure-script can handle the build-stuff in a much more flexible way, without changing files.

**Comment by adrpo** [comment]
I really think we shouldn't support checking out just OMCompiler.
It gets too complicated to configure things and we should keep it simple and make it work only of OpenModelica glue project.
What do say about this?

**Comment by sjoelund** [comment]
You could just rebase your fork to make it pretty :) Or even squash and rebase it.

I am not sure what the rationale of having the testsuite without OpenModelica.git is though.

I think we should support checking out OMCompiler as a separate project, but only for purposes of building it without libraries (i.e. OSX and Linux packages).

**Comment by MarcusWalther** [comment]
I've avoided a checkout of the OpenModelica glue project, because I could not see the log-messages of the submodules. I thought that it's a basic principle of the splitted projects, that I can just pick the parts I need, without the need of a glue project. But if you come to the decision, that we only support the build with the help of the glue project, than it's OK and I can discard my changes.

**Comment by adrpo** [comment]
Yes, truth is that it would be nice to have the possibility to checkout just one submodule and work on that so I think you should keep the changes. I also thought about a better way to handle this if you don't have the glue project but I've come up empty for now, I'll keep thinking about it.

**Comment by lochel** [comment]
I agree with Marcus, since I like to use OMCompiler + OpenModelica-testsuite without using the OpenModelica super-project as well. Why should I download a lot of subprojectes, which I will never use?

**Comment by sjoelund** [comment]
You need to download the OMLibraries project as well. And then you downloaded pretty much all of the projects (OMEdit, OMNotebook, OMOptim are pretty tiny in comparison). Besides, nobody is preventing you from checking out testsuite into OMCompiler/testsuite; then the paths should be correct.

**Comment by adrpo** [comment]
I also agree with you both but the question is how do we handle this without duplicating a lot of functionality from the glue Makefile / configure to the OMCompiler Makefile/configure (same goes for the testsuite and libraries).

**Comment by sjoelund** [comment]
And there is another point to be made. You can simply clone OpenModelica.git and do `git submodule init` only on OMCompiler, libraries, and testsuite. Then you only download the essentials.

**Comment by adrpo** [comment]
An alternative would be to make a minimal glue project including OMCompiler, libraries, and testsuite and some files from the OpenModeilca glue project.

**Comment by MarcusWalther** [comment]
I don't think that we have to duplicate so much, we just have to cleanup the code a little bit. Nearly all of our subprojects have configure-support, so we can pass the important paths to configure, e.g. --with-omc=... and --with-omlibrary=.. (maybe some more). The superproject just has to pass the default values to configure and if somebody wants to use a submodule as standalone, he has to configure it with his system values. I think this will lead to a better style of our projects, because fixed paths like "../../build", that we have used in the past, will disappear.

**Comment by sjoelund** [comment]
I still think you don't need to duplicate any code since you could just not initialize the repositories that you do not need. Fixing that in OpenModelica.git is quite simple (to only configure subprojects that are present).

**Comment by MarcusWalther** [comment]
I agree, that's the simplest solution. We should make it clearer for the users, that they have to checkout the glue-project, otherwise not all features will work as expected.

**Comment by sjoelund** [comment]
https://github.com/OpenModelica/OpenModelica/blob/master/README.md#to-checkout-a-minimal-version-of-openmodelica

**Comment by MarcusWalther** [comment]
Merci

**Pull request closed without merging**
