### PR TITLE
Modelica_Synchronous testing #3560

### PR DESCRIPTION
**Pull request by bernhard-thiele**
Added test for Modelica_Synchronous.

@adrpo What is the best way for creating the test cases? I currently use a relative path to find the way to the reference files repo which I expect to be at the same level as the OpenModelica repo. Should we use a global variable for that?

Also note that the test currently fails since the initial values computed by OMC for the compared variable are `0` but should be `1`.

### CODE REVIEW

**Comment by sjoelund** [comment]
For tests that are added to the testsuite, reference files should be minimal, compressed, and go into testsuite/ReferenceFiles. You cannot use relative paths since partest and rtest use different directory stuctures. You need to use the environment variable used by rtest to point to the testsuite root. See [ModelTesting.mos](https://github.com/OpenModelica/OpenModelica-testsuite/blob/master/simulation/libraries/common/ModelTesting.mos): getEnvironmentVar("REFERENCEFILES")

**Comment by bernhard-thiele** [comment]
Ok, but will getEnvironmentVar("REFERENCEFILES") point to a local copy of the new repository
https://github.com/OpenModelica/LibraryCoverageReferenceResults or will it point to something else?

**Comment by sjoelund** [comment]
It will not point to that repository as it is intended to only be used for the nightly testing, and not the test suite (given by its name).

**Comment by bernhard-thiele** [comment]
@sjoelund, @adrpo, @lochel: I now restructured the tests using the pattern that I found for MSL testing. @sjoelund, is this the way how it should be done?

**Pull request merged**
