### PR TITLE
Fix initialization of variable attributes

### PR DESCRIPTION
**Pull request by lochel**
see OpenModelica/OMCompiler#1573

### CODE REVIEW

**Comment by lochel** [comment]
@adrpo Is the modified xml output of Bug3857.mos correct?

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-25_19-30-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4086/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-25_20-40-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4087/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-25_21-24-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4088/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-27_15-32-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4096/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-28_14-37-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4101/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-28_16-26-00](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4105/console).

**Pull request closed without merging**
