### PR TITLE
added some tests for inStream

### PR DESCRIPTION
**Pull request by vruge**
see: ticket:3885

### CODE REVIEW

**Comment by vruge** [comment]
ping @casella @perost  
- the tests (Test6-Test11) from ticket:3885 will be added
- the tests(Test1-Test5) missing

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-09-01_14-45-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5969/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-09-01_14-58-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5970/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by vruge** [comment]
ping @sjoelund @wibraun 
I don't know how to fix the error messages from Hudson. Can somebody help?

**Comment by sjoelund** [comment]
The file in the Hudson log has trailing whitespace (a space at the end of a line; use the precommit hook up automatically fix these things or setup a text editor to remove trailing whitespace and amend the commit)

**Comment by casella** [comment]
@vitalij I'm not sure what you mean by 'the tests(Test1-Test5) missing'. I would add them all. Even though they won't need the backend module, it's still good that we verify the good behaviour of the front-end

**Comment by vruge** [comment]
@perost should I add Test1-5 here?, or you prefer to add the tests as flattering-tests?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-09-01_20-55-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5971/console).

**Comment by casella** [comment]
@vrugeI have no strong opinion on where the tests should be, as long as they all run. I guess keeping them together is ok

**Comment by vruge** [comment]
@casella @perost I startet new #1019 for the others tests

**Pull request closed without merging**
