### PR TITLE
Extend tests for calculatedParameter, ticket:4027

### PR DESCRIPTION
**Pull request by rfranke**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-18_09-19-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3233/).

**Comment by adrpo** [comment]
@rfranke: "Result xml-file not found" happens if you forgot to add the actual test file that you added to the Makefile. I guess you forgot to add it to your initial commit.

**Comment by sjoelund** [comment]
Do not revert commits by stacking new ones on top. Rebase and squash them all into one.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-18_10-00-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3236/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-10-18_10-18-41](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3237/console).

**Comment by rfranke** [comment]
Which software versions do you use on Hudson?

The new Crane test runs on my machines. I re-import the generated FMU using the Cpp runtime, as opposed to re-importing using the C runtime for the same test with modelExchange/1.0. Noticed that most tests use the C runtime for re-import.

Does re-import with Cpp runtime have an issue on Hudson?

**Comment by sjoelund** [comment]
Ubuntu 14.04.5 LTS on Hudson

**Pull request merged**
