### PR TITLE
update -cppruntime tests

### PR DESCRIPTION
**Pull request by rfranke**

### CODE REVIEW

**Comment by sjoelund** [comment]
Modelica.Electrical.Analog.Examples.ChuaCircuit.mos and Modelica.Fluid.Examples.TraceSubstances.RoomCO2WithControls.mos should use SuppressedSimulation. The warnings are not really relevant and would probably change a lot with new commits.

The alias variables in Fluid are similar, but we can't turn those off easily I think.

**Comment by rfranke** [comment]
Does there exist a VerifiedSuppressedSimulation for RoomCO2WithControls?

**Comment by sjoelund** [comment]
Yes: simulation/libraries/common/ModelTesting.mo has the enumerations

**Comment by rfranke** [comment]
It's a pity that the tests find in a different repository than the compiler -- this requires to maintain two different repos at once and to issue two related pull requests -- misleading people to forget about the tests.

**Comment by sjoelund** [comment]
Fixed by ae6d4ac (your 2 commits, rebased and squashed to remove the cvode add+delete). git commit -a --amend is useful when updating pull requests to change bad parts.

And yes, it's a little bit unfortunate that they are separate repositories. I guess README files can help remedy that.

**Pull request closed without merging**
