### PR TITLE
push MatLabTranslator to Testsuite/special

### PR DESCRIPTION
**Pull request by arun3688**
I messed the previous pull request you can close that request, Here is a new pull request with all the fixes in one commit

### CODE REVIEW

**Comment by sjoelund** [comment]
{{{
OMCompiler/Compiler/FrontEnd/Dump.mo:134 Error: Variable AbsynDumpTpl.dump not found in scope Dump.unparseStr
}}}

**Comment by arun3688** [comment]
No all the compiler sources are loaded and i have updated openmodelica source code, I am not getting any errors like this in windows, Can you test this model and see, In the script.mos can you change the area_inside.m to cube.m and run make test or shall i push the changes

**Comment by sjoelund** [comment]
Oh. I ran it against a clean OMCompiler, which had not created the mo-file of AbsynDump yet. It returns success for me, but... On failure the makefile also gives success, so the test still doesn't do anything.

**Comment by arun3688** [comment]
what you mean by failure,  does the code is not translated

**Comment by sjoelund** [comment]
If I remove some source file, or make the things not work as expected, the makefile still reports success. In order to be a testcase, it needs to be able to report failure.

**Comment by arun3688** [comment]
I just created the make file for easier compilation. It is very similar to ../../../build/bin/omc Script.mos, this is wat the make file does, I don't know how the way to report failures in makefiles , I am sure if any compiler sources changed or removed then the test case will not work.

**Comment by sjoelund** [comment]
mos-scripts can call for example exit(1) on failure.

**Comment by arun3688** [comment]
added failure handle message to mos file

**Comment by arun3688** [comment]
Added status message to mos file for handling failures and squashed to single commit

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-13_13-50-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1164/console).

**Pull request closed without merging**
