### PR TITLE
Update expected output for OMCompiler PR:1034

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-11-18_12-06-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3428/).

**Comment by sjoelund** [comment]
@lochel @wibraun:

userDefinedTearing2.mos says:
> Error: Wrong usage of user defined tearing: The number of tearing variables and residual equations is not identical. Make sure you use user defined tearing as stated in the flag description.

How should the testcase be updated for the new sorting?

scaling1/2.mos I don't know what is going on :)

TanksWithOverflow, Pendulum just fail.

testDASSLnoEquidistant.mos seems weird as well.

Any comments on how to fix these issues?

**Comment by lochel** [comment]
Ping @ptaeuber

**Comment by ptaeuber** [comment]
@sjoelund For userDefinedTearing2.mos use this command now:
`setCommandLineOptions("--preOptModules-=comSubExp --setTearingVars=2,5,7,1,4,5,8 --setResidualEqns=2,3,5,3,2"); getErrorString();`

**Comment by lochel** [comment]
testDASSLnoEquidistant fails due to dynamic state selection. I don’t think that dynamic state selection is needed for the test case, so we could just replace the model to keep the test. @wibraun What do you think?

I will check the two scaling tests later.

**Comment by lochel** [comment]
scaling1/2.mos has two possible solutions. You can just update the expected output to the other solution.
(Probably we could also just remove both test cases …)

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-11-29_14-26-30](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3476/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-11-30_13-04-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3487/console).

**Pull request closed without merging**
