### PR TITLE
Replace matching algorithm that is used by fixInitialSystem

### PR DESCRIPTION
**Pull request by lochel**
see OpenModelica/OMCompiler#261

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-10-31_18-02-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1087/).

**Comment by lochel** [comment]
The failing model `simulation/libraries/3rdParty/GitLibraries/WasteWater.ASM1.Examples.SmallPlant.mos` has not fully specified initial conditions which makes it behaviour not well defined.

**Comment by lochel** [comment]
@adrpo @sjoelund I fixed the initial conditions in the WasteWater library (modelica-3rdparty/WasteWater#7). However, the changes were still not pulled to OMLibraries. Is the Hudson job broken again?

**Comment by sjoelund** [comment]
Yes, it is. I might have fixed it just now :)

**Comment by lochel** [comment]
Unfortunately it’s still broken. Any further idea what is wrong there?

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-11-09_23-16-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1132/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-09_23-53-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1134/console).

**Pull request closed without merging**
