### PR TITLE
Add test case for enumeration redeclaration

### PR DESCRIPTION
**Pull request by gossen**
Testsuite for OpenModelica/OMCompiler#189

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-09-07_20-12-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/725/).

**Comment by adrpo** [comment]
@gossen please update the test Enum5.mo, see the link!

**Comment by gossen** [comment]
It's already done.

**Comment by adrpo** [comment]
Ok, i'll run the pull request again.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-09-07_20-35-26](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/726/console).

**Pull request closed without merging**
