### PR TITLE
updated expected output

### PR DESCRIPTION
**Pull request by jhag**
see OpenModelica/OMCompiler#792

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-28_10-46-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2567/console).

**Comment by lochel** [comment]
The module is disabled for the following examples:
- openmodelica/cppruntime/recordTupleReturnTest.mos
- openmodelica/cruntime/optimization/basic/testAlgLoop5.mos [ticket:3710](https://trac.openmodelica.org/OpenModelica/ticket/3710)
- openmodelica/cruntime/optimization/basic/testAlgLoop6.mos [ticket:3710](https://trac.openmodelica.org/OpenModelica/ticket/3710)
- simulation/libraries/msl32/Modelica.Fluid.Examples.Tanks.TanksWithOverflow.mos [ticket:3874](https://trac.openmodelica.org/OpenModelica/ticket/3874)
- simulation/modelica/nonlinear_system/problem11.mos
- simulation/modelica/others/TestExpressionSolve.mos
- simulation/modelica/others/TestSolve3.mos
- simulation/modelica/others/TestSolve16.mos
- simulation/modelica/others/TestSolve17.mos

**Comment by jhag** [comment]
see Ticket 3711 for /recordTupleReturnTest.mos

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-28_12-03-54](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2570/console).

**Pull request merged**
