### PR TITLE
add MatlabTranslator to Testsuite

### PR DESCRIPTION
**Pull request by arun3688**

### CODE REVIEW

**Comment by sjoelund** [comment]
This test will not be triggered when running the test suite, so it does not make sense to add it to the test suite (unless you add it under testsuite/special and it is run in a separate hook in Hudson).

**Comment by arun3688** [comment]
when i go into the testsuite/special path , the readme file says that test require special software but the translator requires only  omc

**Comment by sjoelund** [comment]
Well, you don't use rtest like the normal tests, so...

**Comment by arun3688** [comment]
Moved the Translator to testsuite/special

**Comment by sjoelund** [comment]
By the way. When you create pull requests, you are recommended to use a topic branch since the pull request tracks the branch you are currently on. You can also change your commit history to not include the first commit (or fix the commit message in the second to move instead of add).

The only error I get is:
```
Running MatlabTranslator
Failed to load compiler sources:
Makefile:4: recipe for target 'test' failed
make: *** [test] Error 1
```

**Pull request closed without merging**
