### PR TITLE
Separation of back end transformations for simulation and initialization

### PR DESCRIPTION
**Pull request by lochel**
Testsuite for OpenModelica/OMCompiler#199

### CODE REVIEW

**Comment by lochel** [comment]
I deactivate some tests for now in coordination with @adrpo. It will be necessary to get all of them working again ASAP. Therefore, I will create tickets for all of these tests (grouped by issue) in the trac system.

**Comment by OpenModelica-Hudson** [comment]
The job failed the testsuite sanity check; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-09-11_10-06-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/755/console) Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-09-11_10-20-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/756/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-09-11_14-18-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/759/console).

**Pull request merged**
