### PR TITLE
skipped intialation for some tests 

### PR DESCRIPTION
**Pull request by vruge**
after structure breaker in  https:/github.com/OpenModelica/OMCompiler/pull/199
- using initialation from file

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-02-20_15-55-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1633/).

**Comment by lochel** [comment]
Why do you need to skip the initialization? Is there something that need to be fixed?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-20_16-29-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1634/console).

**Comment by vruge** [comment]
@lochel In the optimization OMC has some options to handling loop than simulation or initialation and in some cases is a must have. Unfortunately, after "Separation of back end transformations for simulation and initialization" this option limited for initialations.

**Pull request merged**
