### PR TITLE
Generate code with less nested brackets (ticket 3478)

### PR DESCRIPTION
**Pull request by lochel**
Testsuite for OpenModelica/OMCompiler#218.

### CODE REVIEW

**Comment by sjoelund** [comment]
Changing the parenthesis of an expression does not change its result unless you did something wrong, right?

**Comment by lochel** [comment]
The expressions get now evaluated in a different order, which can lead to numerical differences in the results.

**Comment by lochel** [comment]
I needed to update the result files for Modelica.Mechanics.Translational.Examples.Friction, since the result comparison failed for an event point, even though the signals do look the same.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-10-02_08-37-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/867/console).

**Pull request merged**
