### PR TITLE
frontend unitchecking testcases

### PR DESCRIPTION
**Pull request by arun3688**

### CODE REVIEW

**Comment by lochel** [comment]
These tests belong to OpenModelica/OMCompiler#1267.

**Comment by arun3688** [comment]
yes

**Comment by sjoelund** [comment]
https://github.com/OpenModelica/OpenModelica-testsuite/blob/master/Makefile is missing an entry for this new directory

**Comment by arun3688** [comment]
added the Makefile entry

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-12-02_11-17-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3491/).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash testsuite 5ed5e4b1b810c4afde100a609141f3621e88aee0 d93508d2f74ecf0515c666cdf367b386ad32e09f

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-12-02_12-32-02](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3493/console).

**Pull request closed without merging**
